---
title: "assignment 2"
author: "Nikhil Reddy"
date: "2022-09-23"
output:
  html_document:
    df_print: paged
---
```{r}
#package activation to slove lp model.
library(lpSolveAPI)
library(lpSolve)
library(tinytex)
lprec<-make.lp(0,3)

#objective function from the given question.
set.objfn(lprec,c(420,360,300)) 

#adding the constraint values to lp model.
add.constraint(lprec,c(1,1,1),"<=",750)
add.constraint(lprec,c(1,1,1),"<=",900)
add.constraint(lprec,c(1,1,1),"<=",450)
add.constraint(lprec,c(20,15,12),"<=",13000)
add.constraint(lprec,c(20,15,12),"<=",12000)
add.constraint(lprec,c(20,15,12),"<=",5000)
add.constraint(lprec,rep(1,3),"<=",900)
add.constraint(lprec,rep(1,3),"<=",1200)
add.constraint(lprec,rep(1,3),"<=",750)

#set bounds
set.bounds(lprec,lower = c(1,3),columns = c(1,3))
set.bounds(lprec,upper = c(1,20),columns = c(1,3))

#giving names to the rows
rownames<-c("Capacity1","Capacity2","Capacity3","Storage1","Storage2","Storage3","Sales1","Sales2","Sales3")

colnames<-c(paste("Plant",c(1:3),sep = ""))

dimnames(lprec)<-list(rownames,colnames)

#solving the lp model and getting the required objectives,variables and constraints.
solve(lprec)
get.objective(lprec)
get.variables(lprec)
get.constraints(lprec)
```
Objective Function

$$\text{The Objective function is to } Max \hspace{.3cm} Z = 420 (L_1+L_2+L_3) + 360 (M_1+M_2+M_3) + 300 (S_1+S_2+S_3)$$

\$\$

\$\$

$$ \text {which can be written as } Z = 420L_1+360M_1+300S_1+420L_2+360M_2+300S_2+420L_3+360M_3+300S_3
$$

subject to constraints

$$L_1+M_1+S_1\le750$$
$$L_2+M_2+S_2\le900$$
$$L_3+M_3+S_3\le450 $$
$$20L_1+15M_1+12S_1\le13000$$
$$20L_2+15M_2+12S_2\le12000$$
$$20L_3+15M_3+12S_3\le5000$$
$$L_1+L_2+L_3\le900$$
$$M_1+M_2+M_3\le1200$$
$$S_1+S_2+S_3\le750$$
Non negativity constraints
$$L_1, L_2, L_3, M_1, M_2, M_3, S_1, S_2, S_3\ge0 $$
**The above LP problem constaraints can be written as**
$$L_1+M_1+S_1+0L_2+0M_2+0S_2+0L_3+0M_3+0S_3\le750$$
$$0L_1+0M_1+0S_1+L_2+M_2+S_2+0L_3+0M_3+0S_3\le900$$
$$0L_1+0M_1+0S_1+0L_2+0M_2+0S_2+L_3+M_3+S_3\le450$$
$$20L_1+15M_1+12S_1+0L_2+0M_2+0S_2+0L_3+0M_3+0S_3\le13000$$
$$0L_1+0M_1+0S_1+20L_2+15M_2+12S_2+0L_3+0M_3+0S_3\le12000$$
$$0L_1+0M_1+0S_1+0L_2+0M_2+0S_2+20L_3+15M_3+12S_3\le5000$$
$$L_1+0M_1+0S_1+L_2+0M_2+0S_2+L_3+0M_3+0S_3\le900$$
$$0L_1+M_1+0S_1+0L_2+M_2+0S_2+0L_3+M_3+0S_3\le1200$$
$$0L_1+0M_1+S_1+0L_2+0M_2+S_2+0L_3+0M_3+S_3\le750$$
```{r}
#objective function
f.obj<-c(420,360,300,420,360,300,420,360,300)

#Constraints
f.con<-matrix(c(1, 1, 1, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 1, 1, 1, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 1, 1, 1,
                20, 15, 12, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 20, 15, 12, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 20, 15, 12,
                1, 0, 0, 1, 0, 0, 1, 0, 0,
                0, 1, 0, 0, 1, 0, 0, 1, 0,
                0, 0, 1, 0, 0, 1, 0, 0, 1), nrow = 9, byrow = TRUE)

#set inequality signs
f.dir<- c("<=", "<=", "<=", "<=", "<=", "<=", "<=", "<=", "<=" )

#set right hand side coefficients
f.rhs<-c(750, 900, 450, 13000, 12000, 5000, 900, 1200, 750)

#value of z
lp("max", f.obj, f.con, f.dir, f.rhs)

#value of the variables
lp("max", f.obj, f.con, f.dir, f.rhs)$solution
```


